#pragma once

enum MIRROR {
    HARDWARE,
    HORIZONTAL,
    VERTICAL,
    FOUR_SCREEN,
    ONE_SCREEN_LO,
    ONE_SCREEN_HI,
    DIAGONAL,
    L_SHAPED,
    THREE_SCREEN_VERTICAL,
    THREE_SCREEN_HORIZONTAL,
    ONE_SCREEN_FIXED
};